<a href="https://colab.research.google.com/github/deep1003/deep1003/blob/master/Week%2004.%20Data%20and%20Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)
df

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

from matplotlib import pyplot as plt
df['Age'].plot(kind='hist', bins=20, title='Age')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Name').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('City').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Age']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Age'}, axis=1)
              .sort_values('Age', ascending=True))
  xs = counted['Age']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values('Age', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Name')):
  _plot_series(series, series_name, i)
  fig.legend(title='Name', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Age')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Age']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Age'}, axis=1)
              .sort_values('Age', ascending=True))
  xs = counted['Age']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values('Age', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('City')):
  _plot_series(series, series_name, i)
  fig.legend(title='City', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Age')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
df['Age'].plot(kind='line', figsize=(8, 4), title='Age')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['City'].value_counts()
    for x_label, grp in df.groupby('Name')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Name')
_ = plt.ylabel('City')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Age', y='Name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['City'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Age', y='City', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [32]:
# Creating a list with mixed data types
my_list = [1, "apple", 3.5]

# Accessing list elements by index
print("First element:", my_list[0])  # Access the first element
print("Second element:", my_list[1])  # Access the second element
print("Third element:", my_list[2])  # Access the third element

# Adding an element to the list
my_list.append('new item')

# Displaying the updated lis
my_list[0]


First element: 1
Second element: apple
Third element: 3.5


1

In [25]:
# Nested list
data_list1 = [['Alice', 25, 'New York']]
data_list1[0][1]

25

In [30]:
#display the data_list
data_list1 = [['Alice', 25, 'New York'], ['Bob', 30, 'Los Angeles'], ['Charlie', 35, 'Chicago']]
data_list1

[['Alice', 25, 'New York'],
 ['Bob', 30, 'Los Angeles'],
 ['Charlie', 35, 'Chicago']]

In [40]:
import numpy as np


# Defining a matrix (2D array)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
matrix[1][1]

5

In [42]:
import numpy as np

# Defining a matrix (2D array)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Accessing the element at row 1, column 1 (remember Python uses zero-based indexing)
matrix[1][1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5

In [57]:
vector = np.array([1, 2, 3])
vector

array([1, 2, 3])

In [60]:
vector[0][1]

IndexError: invalid index to scalar variable.

In [61]:
type(vector)

numpy.ndarray

In [62]:
type(matrix)

numpy.ndarray

In [64]:
vector1 = np.array(["1", "2", "3"])
vector1

array(['1', '2', '3'], dtype='<U1')

In [65]:
type(vector1)

numpy.ndarray

In [66]:
# Nested list
my_list = [[1, "apple", 3.5],
           [2, "car", 4.5],
           [3, "bob", 5.5]]

# Display "apple"
print(my_list[0][1])  # Access the second element from the first nested list


apple


In [ ]:
import numpy as np

# Nested list
my_list = [[1, "apple", 3.5],
           [2, "car", 4.5],
           [3, "bob", 5.5]]

# Convert nested list to matrix (numpy array)
matrix = np.array(my_list)

# Display the matrix
print(matrix)


In [67]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# Perform matrix multiplication
C = np.dot(A, B)

# Display the result
print("Matrix C:\n", C)


Matrix C:
 [[ 58  64]
 [139 154]]
